[archive]
nanazip_exe = "../../nz/Nanazip.Console.exe"

# Package Configuration
[packages]

# Package: test
[packages.name]
id = ""
name = ""
description = ""
version_url = "https://" #=-- Raw URL to file
filelist_url = "https://" #=-- Raw URL to file
repo_url = "https://" #=-- Raw URL to the folder with files
output_path = ""
password = "" #=-- The Archive's Password. Leave this empty for no password